### ISSUE TITLE
Doesn't build with dcmtk-3.6.4

### ISSUE THREAD

**Issue by yurivict** [jenslody/aeskulap#14]
```
poolassociation.cpp:123:7: error: no matching function for call to 'DU_findSOPClassAndInstanceInDataSet'
        if (!DU_findSOPClassAndInstanceInDataSet(dataset, sopClass, sopInstance))
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/dcmtk/dcmnet/diutil.h:110:28: note: candidate function not viable: requires at least 5 arguments, but 3 were provided
DCMTK_DCMNET_EXPORT OFBool DU_findSOPClassAndInstanceInDataSet(
                           ^
1 error generated.
gmake[3]: *** [Makefile:623: poolassociation.lo] Error 1
gmake[3]: *** Waiting for unfinished jobs....
poolfindassociation.cpp:26:34: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        Association::m_abstractSyntax = UID_FINDPatientRootQueryRetrieveInformationModel;
                                        ^
/usr/local/include/dcmtk/dcmdata/dcuid.h:564:68: note: expanded from macro 'UID_FINDPatientRootQueryRetrieveInformationModel'
#define UID_FINDPatientRootQueryRetrieveInformationModel           "1.2.840.10008.5.1.4.1.2.1.1"
                                                                   ^
poolfindassociation.cpp:60:9: error: no matching function for call to 'DIMSE_findUser'
        cond = DIMSE_findUser(assoc, presId, &req, query, 
               ^~~~~~~~~~~~~~
```

**Comment by stefanhusmann** [comment]
confirmed for Arch Linux, though the error messages are abi different
''' shell
poolassociation.cpp: In member function 'virtual OFCondition Association::SendObject(DcmDataset*)':
poolassociation.cpp:123:73: error: invalid conversion from 'char*' to 'size_t {aka long unsigned int}' [-fpermissive]
  if (!DU_findSOPClassAndInstanceInDataSet(dataset, sopClass, sopInstance))
                                                                         ^
poolassociation.cpp:123:73: error: too few arguments to function 'bool DU_findSOPClassAndInstanceInDataSet(DcmItem*, char*, size_t, char*, size_t, bool)'
In file included from poolassociation.cpp:24:0:
/usr/include/dcmtk/dcmnet/diutil.h:110:28: note: declared here
 DCMTK_DCMNET_EXPORT OFBool DU_findSOPClassAndInstanceInDataSet(
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:623: poolassociation.lo] Error 1

'''

**Comment by moesasji** [comment]
I've tried to build this on Slackware current and am running into exactly the same error message as above for Arch Linux. This build-failure appears to be generated by the following patch of dcmtk from the 11th of May: 

http://git.dcmtk.org/?p=dcmtk.git;a=commitdiff;h=e4f702640f9d96142df3868cff3881605eeb4ed5#patch5

This might help narrow down where the problem is.
